# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1541740038);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1541688052);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1541747478);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1541739918);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1541743758);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1541688172);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/student/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1541438939687");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1541440752687");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1541747004161");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1541750604161");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.slowStartup.averageTime", 6079);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160907070339");
user_pref("browser.startup.homepage_override.mstone", "45.4.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1541525250407");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1541438912578");
user_pref("datareporting.policy.firstRunTime", "1541438850406");
user_pref("datareporting.sessions.current.activeTicks", 263);
user_pref("datareporting.sessions.current.firstPaint", 6319);
user_pref("datareporting.sessions.current.main", 3172);
user_pref("datareporting.sessions.current.sessionRestored", 7491);
user_pref("datareporting.sessions.current.startTime", "1541739794018");
user_pref("datareporting.sessions.current.totalTime", 7880);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1541438846329,\"a\":47,\"t\":381,\"c\":false,\"m\":2532,\"fp\":5963,\"sr\":6261}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1541687929121,\"a\":57,\"t\":450,\"c\":false,\"m\":2132,\"fp\":4925,\"sr\":5302}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1541740039);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.4.0");
user_pref("extensions.lastPlatformVersion", "45.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1473246881000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1473246880000}}}");
user_pref("gecko.buildID", "20160907070339");
user_pref("gecko.mstone", "45.4.0");
user_pref("gfx.crash-guard.glcontext.appVersion", "45.4.0");
user_pref("gfx.crash-guard.glcontext.deviceID", "Gallium 0.4 on llvmpipe (LLVM 3.8, 256 bits)");
user_pref("gfx.crash-guard.glcontext.driverVersion", "2.1 Mesa 11.2.2");
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("idle.lastDailyNotification", 1541688431);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1541438914);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160907070339");
user_pref("media.gmp-manager.lastCheck", 1541687995);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 48221);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1541739797);
user_pref("toolkit.telemetry.cachedClientID", "57d009f1-1106-4b1f-8189-a563b4f60f39");
user_pref("toolkit.telemetry.previousBuildID", "20160907070339");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
